trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: "run setup scripts to install testing modules"
  inputs:
    filePath: 'tests/tests-setup.ps1'
    
- task: PowerShell@2
  displayName: "run pester tests"
  inputs:
    targetType: 'inline'
    script: |
      Invoke-Pester tests