trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    filePath: 'scripts/setup.ps1'
    
- task: PowerShell@2
  inputs:
    filePath: 'scripts/teams.ps1'

- task: PowerShell@2
  inputs:
    filePath: 'scripts/domains.ps1'

- task: PowerShell@2
  inputs:
    filePath: 'scripts/systems.ps1'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: 'output/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
